<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NACTS-081729" name="ChromeTest" tests="131" failures="30" timestamp="25 Apr 2017 23:19:06 GMT" time="7307.329" errors="0">
  <testcase name="viewBalanceHistoryDetailsRegisteredDynamic" time="95.162" classname="automationFramework.TestCases.BalanceHistoryTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at automationFramework.PageObjects.BalanceHistoryPage.clickRow(BalanceHistoryPage.java:93)
	at automationFramework.TestCases.BalanceHistoryTest.viewBalanceHistoryDetailsRegisteredDynamic(BalanceHistoryTest.java:113)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- viewBalanceHistoryDetailsRegisteredDynamic -->
  <testcase name="viewBalanceHistoryFilterTest" time="75.536" classname="automationFramework.TestCases.BalanceHistoryTest"/>
  <testcase name="viewBalanceHistoryRegisteredDynamic" time="70.087" classname="automationFramework.TestCases.BalanceHistoryTest"/>
  <testcase name="viewBalanceHistoryUnregisteredDynamic" time="180.424" classname="automationFramework.TestCases.BalanceHistoryTest"/>
  <testcase name="createNewCustomerApi" time="8.434" classname="automationFramework.TestCases.CreateCustomerAPITest">
    <failure type="java.lang.AssertionError" message="expected [4033311371] but found [4033311371,undefined,undefined]">
      <![CDATA[java.lang.AssertionError: expected [4033311371] but found [4033311371,undefined,undefined]
	at automationFramework.TestCases.CreateCustomerAPITest.createNewCustomerApi(CreateCustomerAPITest.java:73)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- createNewCustomerApi -->
  <testcase name="createNewCustomerDBCheckContactTable" time="16.98" classname="automationFramework.TestCases.CreateCustomerDBTest"/>
  <testcase name="createNewCustomerDBCheckAccountTable" time="13.737" classname="automationFramework.TestCases.CreateCustomerDBTest"/>
  <testcase name="createNewCustomerDBCheckAddressTable" time="13.637" classname="automationFramework.TestCases.CreateCustomerDBTest"/>
  <testcase name="createNewCustomerDBCheckSecurityTable" time="13.169" classname="automationFramework.TestCases.CreateCustomerDBTest"/>
  <testcase name="createNewCustomerDBCheckPhoneTable" time="13.521" classname="automationFramework.TestCases.CreateCustomerDBTest"/>
  <testcase name="createNewCustomerCancelDBCheck" time="7.82" classname="automationFramework.TestCases.CreateCustomerDBTest"/>
  <testcase name="createNewCustomer" time="14.504" classname="automationFramework.TestCases.CreateCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [2063354211] but found [2063354211,undefined,undefined]">
      <![CDATA[java.lang.AssertionError: expected [2063354211] but found [2063354211,undefined,undefined]
	at automationFramework.TestCases.CreateCustomerTest.createNewCustomer(CreateCustomerTest.java:62)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- createNewCustomer -->
  <testcase name="createCustomerCancel" time="8.716" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createCustomerContactTypeNotSelected" time="10.035" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createCustomerInvalidEmail" time="12.161" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createCustomerInvalidPin" time="9.562" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createCustomerInvalidUserName" time="9.451" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createCustomerDuplicateUserName" time="22.985" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createCustomerInvalidPhone" time="7.941" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createCustomerNameMissing" time="6.617" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createCustomerEmailMissing" time="7.008" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createCustomerInvalidPin2" time="13.201" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createCustomerPostalCodeMissing" time="13.04" classname="automationFramework.TestCases.CreateCustomerTest"/>
  <testcase name="createNewCustomerGmailPlus" time="14.526" classname="automationFramework.TestCases.CreateCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [2467613571] but found [2467613571,undefined,undefined]">
      <![CDATA[java.lang.AssertionError: expected [2467613571] but found [2467613571,undefined,undefined]
	at automationFramework.TestCases.CreateCustomerTest.createNewCustomerGmailPlus(CreateCustomerTest.java:357)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- createNewCustomerGmailPlus -->
  <testcase name="createFundingSource" time="13.582" classname="automationFramework.TestCases.CreateFundingTest"/>
  <testcase name="createFundingSourceNewBillingAddress" time="17.529" classname="automationFramework.TestCases.CreateFundingTest"/>
  <testcase name="createFundingSourceCancel" time="73.231" classname="automationFramework.TestCases.CreateFundingTest"/>
  <testcase name="createFundingSourceTypeNotSelected" time="14.137" classname="automationFramework.TestCases.CreateFundingTest"/>
  <testcase name="createCustomerInvalidEmail" time="12.709" classname="automationFramework.TestCases.CreateFundingTest"/>
  <testcase name="createCustomerFundingInvalidCC" time="17.799" classname="automationFramework.TestCases.CreateFundingTest"/>
  <testcase name="createCustomerFundingInvalidName" time="13.799" classname="automationFramework.TestCases.CreateFundingTest"/>
  <testcase name="createFundingSourceInvalidPanTooLong" time="13.946" classname="automationFramework.TestCases.CreateFundingTest"/>
  <testcase name="createFundingSourceInvalidCCType" time="15.608" classname="automationFramework.TestCases.CreateFundingTest"/>
  <testcase name="createFundingSourceInvalidExpirationDate" time="13.561" classname="automationFramework.TestCases.CreateFundingTest"/>
  <testcase name="createFundingSourceTwoCards" time="18.812" classname="automationFramework.TestCases.CreateFundingTest"/>
  <testcase name="createFundingSourceChangePrimaryCard" time="25.616" classname="automationFramework.TestCases.CreateFundingTest"/>
  <testcase name="createOrderDBcheck" time="25.811" classname="automationFramework.TestCases.CreateOrderDBTest"/>
  <testcase name="createOrderCancelDBcheck" time="20.902" classname="automationFramework.TestCases.CreateOrderDBTest"/>
  <testcase name="createOrderSubmit" time="26.637" classname="automationFramework.TestCases.CreateOrderTest"/>
  <testcase name="createOrderExpiredCard" time="17.179" classname="automationFramework.TestCases.CreateOrderTest"/>
  <testcase name="createOrderCancel" time="16.157" classname="automationFramework.TestCases.CreateOrderTest"/>
  <testcase name="createOrderNewFundingSource" time="23.329" classname="automationFramework.TestCases.CreateOrderTest">
    <failure type="org.openqa.selenium.WebDriverException" message="unknown error: Element &amp;lt;button class=&amp;quot;btn btn-primary cmc btn-sm&amp;quot; id=&amp;quot;orderCreationFrom_submit_button&amp;quot; type=&amp;quot;submit&amp;quot;&amp;gt;...&amp;lt;/button&amp;gt; is not clickable at point (34, 473). Other element would receive the click: &amp;lt;div class=&amp;quot;ui-widget-overlay ui-dialog-mask&amp;quot; style=&amp;quot;z-index: 1004;&amp;quot;&amp;gt;&amp;lt;/div&amp;gt;
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.28.455520 (cc17746adff54984afff480136733114c6b3704b),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 54 milliseconds
Build info: version: &amp;apos;3.0.1&amp;apos;, revision: &amp;apos;1969d75&amp;apos;, time: &amp;apos;2016-10-18 09:49:13 -0700&amp;apos;
System info: host: &amp;apos;NACTS-081729&amp;apos;, ip: &amp;apos;149.63.89.30&amp;apos;, os.name: &amp;apos;Windows 7&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;6.1&amp;apos;, java.version: &amp;apos;1.8.0_77&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.28.455520 (cc17746adff54984afff480136733114c6b3704b), userDataDir=C:\Users\200123\AppData\Local\Temp\scoped_dir26484_24604}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=57.0.2987.133, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: f99e4e9e9abc346a904c0be2ca3fd669">
      <![CDATA[org.openqa.selenium.WebDriverException: unknown error: Element <button class="btn btn-primary cmc btn-sm" id="orderCreationFrom_submit_button" type="submit">...</button> is not clickable at point (34, 473). Other element would receive the click: <div class="ui-widget-overlay ui-dialog-mask" style="z-index: 1004;"></div>
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.28.455520 (cc17746adff54984afff480136733114c6b3704b),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 54 milliseconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'NACTS-081729', ip: '149.63.89.30', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_77'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.28.455520 (cc17746adff54984afff480136733114c6b3704b), userDataDir=C:\Users\200123\AppData\Local\Temp\scoped_dir26484_24604}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=57.0.2987.133, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: f99e4e9e9abc346a904c0be2ca3fd669
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:274)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
	at automationFramework.PageObjects.CreateOrderPage.clickSubmit(CreateOrderPage.java:52)
	at automationFramework.TestCases.CreateOrderTest.createOrderNewFundingSource(CreateOrderTest.java:165)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- createOrderNewFundingSource -->
  <testcase name="registerNewCustomerNoRecordFound" time="45.669" classname="automationFramework.TestCases.CreateUnregistredCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [8265725406] but found [8265725406,undefined,undefined]">
      <![CDATA[java.lang.AssertionError: expected [8265725406] but found [8265725406,undefined,undefined]
	at automationFramework.TestCases.CreateUnregistredCustomerTest.verifyNewCustomerCreation(CreateUnregistredCustomerTest.java:185)
	at automationFramework.TestCases.CreateUnregistredCustomerTest.registerNewCustomerNoRecordFound(CreateUnregistredCustomerTest.java:63)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- registerNewCustomerNoRecordFound -->
  <testcase name="registerNewCustomerTranistTokenFound" time="52.519" classname="automationFramework.TestCases.CreateUnregistredCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [5353451375] but found [5353451375,undefined,undefined]">
      <![CDATA[java.lang.AssertionError: expected [5353451375] but found [5353451375,undefined,undefined]
	at automationFramework.TestCases.CreateUnregistredCustomerTest.verifyNewCustomerCreation(CreateUnregistredCustomerTest.java:185)
	at automationFramework.TestCases.CreateUnregistredCustomerTest.registerNewCustomerTranistTokenFound(CreateUnregistredCustomerTest.java:104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- registerNewCustomerTranistTokenFound -->
  <testcase name="registerNewCustomerInvalidToken" time="16.892" classname="automationFramework.TestCases.CreateUnregistredCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [2722157441] but found [2722157441,undefined,undefined]">
      <![CDATA[java.lang.AssertionError: expected [2722157441] but found [2722157441,undefined,undefined]
	at automationFramework.TestCases.CreateUnregistredCustomerTest.verifyNewCustomerCreation(CreateUnregistredCustomerTest.java:185)
	at automationFramework.TestCases.CreateUnregistredCustomerTest.registerNewCustomerInvalidToken(CreateUnregistredCustomerTest.java:130)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- registerNewCustomerInvalidToken -->
  <testcase name="registerNewCustomerSubysystemPage" time="86.707" classname="automationFramework.TestCases.CreateUnregistredCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [6556762132] but found [6556762132,undefined,undefined]">
      <![CDATA[java.lang.AssertionError: expected [6556762132] but found [6556762132,undefined,undefined]
	at automationFramework.TestCases.CreateUnregistredCustomerTest.verifyNewCustomerCreation(CreateUnregistredCustomerTest.java:185)
	at automationFramework.TestCases.CreateUnregistredCustomerTest.registerNewCustomerSubysystemPage(CreateUnregistredCustomerTest.java:168)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- registerNewCustomerSubysystemPage -->
  <testcase name="deleteFundingSource" time="15.09" classname="automationFramework.TestCases.DeleteFundingTest"/>
  <testcase name="deleteFundingSourceClose" time="14.673" classname="automationFramework.TestCases.DeleteFundingTest"/>
  <testcase name="deleteFundingSourceCancel" time="14.373" classname="automationFramework.TestCases.DeleteFundingTest"/>
  <testcase name="checkEmailNewCustomer" time="75.207" classname="automationFramework.TestCases.EmailTest"/>
  <testcase name="checkEmailCreateOrder" time="322.438" classname="automationFramework.TestCases.EmailTest"/>
  <testcase name="checkEmailLinkAccount" time="210.621" classname="automationFramework.TestCases.EmailTest"/>
  <testcase name="checkEmailUpdateContact" time="20.831" classname="automationFramework.TestCases.EmailTest">
    <failure type="java.lang.AssertionError" message="expected [indy] but found [robert]">
      <![CDATA[java.lang.AssertionError: expected [indy] but found [robert]
	at automationFramework.TestCases.CoreTest.updateContact(CoreTest.java:104)
	at automationFramework.TestCases.EmailTest.checkEmailUpdateContact(EmailTest.java:167)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- checkEmailUpdateContact -->
  <testcase name="checkEmailResetPassword" time="832.559" classname="automationFramework.TestCases.EmailTest">
    <failure type="java.lang.AssertionError" message="Password Reset Verification Email Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Password Reset Verification Email Test Failed expected [true] but found [false]
	at automationFramework.TestCases.EmailTest.checkEmailResetPassword(EmailTest.java:198)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- checkEmailResetPassword -->
  <testcase name="checkEmailDeleteFunding" time="21.954" classname="automationFramework.TestCases.EmailTest">
    <failure type="java.lang.AssertionError" message="Customer Funding Source Update Email Test Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Customer Funding Source Update Email Test Failed expected [true] but found [false]
	at automationFramework.TestCases.EmailTest.checkEmailDeleteFunding(EmailTest.java:227)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- checkEmailDeleteFunding -->
  <testcase name="linkAccountTest" time="251.863" classname="automationFramework.TestCases.LinkAccountAPITest"/>
  <testcase name="linkAccountAlreadyLinkedTest" time="266.965" classname="automationFramework.TestCases.LinkAccountAPITest"/>
  <testcase name="linkAccountFailureTest" time="11.333" classname="automationFramework.TestCases.LinkAccountAPITest"/>
  <testcase name="linkAccountCancelTest" time="11.938" classname="automationFramework.TestCases.LinkAccountAPITest"/>
  <testcase name="linkAccountCardExpirationMissingTest" time="11.389" classname="automationFramework.TestCases.LinkAccountAPITest"/>
  <testcase name="linkAccountBankAccountMissingTest" time="13.069" classname="automationFramework.TestCases.LinkAccountAPITest"/>
  <testcase name="linkAccountMessageTest" time="303.267" classname="automationFramework.TestCases.LinkAccountAPITest"/>
  <testcase name="createLinkAccountDBcheck" time="301.903" classname="automationFramework.TestCases.LinkAccountDBTest"/>
  <testcase name="createLinkAccountCancellDBcheck" time="306.201" classname="automationFramework.TestCases.LinkAccountDBTest"/>
  <testcase name="linkAccountTest" time="262.708" classname="automationFramework.TestCases.LinkAccountTest"/>
  <testcase name="linkAccountAlreadyLinkedTest" time="271.724" classname="automationFramework.TestCases.LinkAccountTest"/>
  <testcase name="linkAccountFailureTest" time="20.015" classname="automationFramework.TestCases.LinkAccountTest"/>
  <testcase name="linkAccountCancelTest" time="19.168" classname="automationFramework.TestCases.LinkAccountTest"/>
  <testcase name="linkAccountCardExpirationMissingTest" time="11.274" classname="automationFramework.TestCases.LinkAccountTest"/>
  <testcase name="linkAccountBankAccountMissingTest" time="10.914" classname="automationFramework.TestCases.LinkAccountTest"/>
  <testcase name="linkAccountMessageTest" time="302.84" classname="automationFramework.TestCases.LinkAccountTest"/>
  <testcase name="resetPassword" time="10.044" classname="automationFramework.TestCases.ResetPasswordTest">
    <failure type="java.lang.AssertionError" message="expected [Reset Password Confirmation] but found []">
      <![CDATA[java.lang.AssertionError: expected [Reset Password Confirmation] but found []
	at automationFramework.TestCases.ResetPasswordTest.resetPassword(ResetPasswordTest.java:55)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- resetPassword -->
  <testcase name="resetPasswordCancel" time="10.343" classname="automationFramework.TestCases.ResetPasswordTest"/>
  <testcase name="resetPasswordClose" time="10.969" classname="automationFramework.TestCases.ResetPasswordTest">
    <failure type="java.lang.AssertionError" message="expected [Reset Password Confirmation] but found []">
      <![CDATA[java.lang.AssertionError: expected [Reset Password Confirmation] but found []
	at automationFramework.TestCases.ResetPasswordTest.resetPasswordClose(ResetPasswordTest.java:79)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- resetPasswordClose -->
  <testcase name="searchCustomerVerifiedTest" time="9.124" classname="automationFramework.TestCases.SearchTest">
    <failure type="java.lang.AssertionError" message="expected [4033311371] but found [4033311371,undefined,undefined]">
      <![CDATA[java.lang.AssertionError: expected [4033311371] but found [4033311371,undefined,undefined]
	at automationFramework.TestCases.SearchTest.searchCustomerVerifiedTest(SearchTest.java:76)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- searchCustomerVerifiedTest -->
  <testcase name="searchCustomerNotVerifiedTest" time="10.189" classname="automationFramework.TestCases.SearchTest"/>
  <testcase name="searchCustomerNoResultsTest" time="8.928" classname="automationFramework.TestCases.SearchTest"/>
  <testcase name="searchCustomerTypeNotSelected" time="8.465" classname="automationFramework.TestCases.SearchTest"/>
  <testcase name="searchCustomerInvalidEmail" time="7.101" classname="automationFramework.TestCases.SearchTest"/>
  <testcase name="searchCustomerCheckDuplicateTestFname" time="7.248" classname="automationFramework.TestCases.SearchTest">
    <failure type="java.lang.AssertionError" message="expected [robert] but found [Robert]">
      <![CDATA[java.lang.AssertionError: expected [robert] but found [Robert]
	at automationFramework.TestCases.SearchTest.searchCustomerCheckDuplicateTestFname(SearchTest.java:176)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- searchCustomerCheckDuplicateTestFname -->
  <testcase name="searchCustomerCheckDuplicateTestLname" time="9.934" classname="automationFramework.TestCases.SearchTest"/>
  <testcase name="searchCustomerCheckDuplicateTestFnameLname" time="7.461" classname="automationFramework.TestCases.SearchTest2"/>
  <testcase name="searchCustomerCheckDuplicateTestPhone" time="17.929" classname="automationFramework.TestCases.SearchTest2">
    <failure type="java.lang.AssertionError" message="expected [7362133160] but found [7362133160,undefined,undefined]">
      <![CDATA[java.lang.AssertionError: expected [7362133160] but found [7362133160,undefined,undefined]
	at automationFramework.TestCases.SearchTest2.searchCustomerCheckDuplicateTestPhone(SearchTest2.java:76)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- searchCustomerCheckDuplicateTestPhone -->
  <testcase name="searchCustomerCheckDuplicateTestEmail" time="7.393" classname="automationFramework.TestCases.SearchTest2"/>
  <testcase name="searchCustomerCheckDuplicateTestEmailPhone" time="7.56" classname="automationFramework.TestCases.SearchTest2">
    <failure type="java.lang.AssertionError" message="expected [7362133160] but found [7362133160,undefined,undefined]">
      <![CDATA[java.lang.AssertionError: expected [7362133160] but found [7362133160,undefined,undefined]
	at automationFramework.TestCases.SearchTest2.searchCustomerCheckDuplicateTestEmailPhone(SearchTest2.java:103)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- searchCustomerCheckDuplicateTestEmailPhone -->
  <testcase name="searchCustomerCheckDuplicateTestAll" time="8.297" classname="automationFramework.TestCases.SearchTest2">
    <failure type="java.lang.AssertionError" message="expected [7362133160] but found [7362133160,undefined,undefined]">
      <![CDATA[java.lang.AssertionError: expected [7362133160] but found [7362133160,undefined,undefined]
	at automationFramework.TestCases.SearchTest2.searchCustomerCheckDuplicateTestAll(SearchTest2.java:122)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- searchCustomerCheckDuplicateTestAll -->
  <testcase name="searchNewSearchButton" time="9.964" classname="automationFramework.TestCases.SearchTest2"/>
  <testcase name="searchCustomerVerifiedThreeInfoTest" time="9.444" classname="automationFramework.TestCases.SearchTest2">
    <failure type="java.lang.AssertionError" message="expected [4033311371] but found [4033311371,undefined,undefined]">
      <![CDATA[java.lang.AssertionError: expected [4033311371] but found [4033311371,undefined,undefined]
	at automationFramework.TestCases.SearchTest2.searchCustomerVerifiedThreeInfoTest(SearchTest2.java:232)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- searchCustomerVerifiedThreeInfoTest -->
  <testcase name="searchCustomerNotVerifiedThreeInfoTest" time="8.964" classname="automationFramework.TestCases.SearchTest2">
    <failure type="java.lang.AssertionError" message="expected [4033311371] but found [4033311371,undefined,undefined]">
      <![CDATA[java.lang.AssertionError: expected [4033311371] but found [4033311371,undefined,undefined]
	at automationFramework.TestCases.SearchTest2.searchCustomerNotVerifiedThreeInfoTest(SearchTest2.java:277)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- searchCustomerNotVerifiedThreeInfoTest -->
  <testcase name="searchCustomerClickNotVerified" time="8.839" classname="automationFramework.TestCases.SearchTest2">
    <failure type="java.lang.AssertionError" message="expected [4033311371] but found [4033311371,undefined,undefined]">
      <![CDATA[java.lang.AssertionError: expected [4033311371] but found [4033311371,undefined,undefined]
	at automationFramework.TestCases.SearchTest2.searchCustomerClickNotVerified(SearchTest2.java:309)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- searchCustomerClickNotVerified -->
  <testcase name="tokenVerificationLinkAccount" time="16.715" classname="automationFramework.TestCases.TokenSearchAPITest"/>
  <testcase name="tokenVerificationLinkAccountNewSearch" time="13.451" classname="automationFramework.TestCases.TokenSearchAPITest"/>
  <testcase name="searchTokenInvalidMonth" time="8.314" classname="automationFramework.TestCases.TokenSearchTest"/>
  <testcase name="searchTokenInvalidYear" time="7.314" classname="automationFramework.TestCases.TokenSearchTest"/>
  <testcase name="searchTokenMissingBankCard" time="6.933" classname="automationFramework.TestCases.TokenSearchTest"/>
  <testcase name="searchTokenNewSearch" time="7.84" classname="automationFramework.TestCases.TokenSearchTest"/>
  <testcase name="searchTokenNoRecordFound" time="8.389" classname="automationFramework.TestCases.TokenSearchTest"/>
  <testcase name="searchTokenNoRecordFoundNewSearch" time="8.203" classname="automationFramework.TestCases.TokenSearchTest"/>
  <testcase name="searchTokenInvalidTokenSearch" time="7.955" classname="automationFramework.TestCases.TokenSearchTest"/>
  <testcase name="searchTokenInvalidTokenNewSearch" time="8.376" classname="automationFramework.TestCases.TokenSearchTest"/>
  <testcase name="searchUnregistredCustomer" time="19.042" classname="automationFramework.TestCases.TokenSearchTest"/>
  <testcase name="searchRegistredCustomer" time="43.977" classname="automationFramework.TestCases.TokenSearchTest"/>
  <testcase name="searchRegistredCustomerVerifiedThreeInfo" time="40.972" classname="automationFramework.TestCases.TokenSearchTest"/>
  <testcase name="viewRegistredCustomerSubsystemPage" time="44.176" classname="automationFramework.TestCases.TokenSearchTest"/>
  <testcase name="searchTokenVerification" time="13.654" classname="automationFramework.TestCases.TokenSearchTest"/>
  <testcase name="tokenSearchAuthenticationError" time="8.398" classname="automationFramework.TestCases.TokenSearchTest"/>
  <testcase name="tokenSearchWithSpace" time="41.758" classname="automationFramework.TestCases.TokenSearchTest"/>
  <testcase name="searchTokenClickHome" time="14.252" classname="automationFramework.TestCases.TokenSearchTest"/>
  <testcase name="viewTravelHistoryRegistredCustomerSubAccount" time="434.15" classname="automationFramework.TestCases.TravelHistoryTest">
    <failure type="java.lang.AssertionError" message="expected [$2.50] but found [$10.00]">
      <![CDATA[java.lang.AssertionError: expected [$2.50] but found [$10.00]
	at automationFramework.TestCases.TravelHistoryTest.viewTravelHistoryRegistredCustomerSubAccount(TravelHistoryTest.java:143)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- viewTravelHistoryRegistredCustomerSubAccount -->
  <testcase name="viewTravelHistoryUnregistredCustomer" time="418.915" classname="automationFramework.TestCases.TravelHistoryTest">
    <failure type="java.lang.AssertionError" message="expected [$2.50] but found [$10.00]">
      <![CDATA[java.lang.AssertionError: expected [$2.50] but found [$10.00]
	at automationFramework.TestCases.TravelHistoryTest.viewTravelHistoryUnregistredCustomer(TravelHistoryTest.java:86)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- viewTravelHistoryUnregistredCustomer -->
  <testcase name="addNewAddress" time="8.904" classname="automationFramework.TestCases.UpdateAddressTest">
    <failure type="java.lang.AssertionError" message="expected [4033311371] but found [4033311371,undefined,undefined]">
      <![CDATA[java.lang.AssertionError: expected [4033311371] but found [4033311371,undefined,undefined]
	at automationFramework.TestCases.UpdateAddressTest.addNewAddress(UpdateAddressTest.java:59)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- addNewAddress -->
  <testcase name="addNewAddressCancel" time="193.866" classname="automationFramework.TestCases.UpdateAddressTest"/>
  <testcase name="updateAddress" time="8.907" classname="automationFramework.TestCases.UpdateAddressTest">
    <failure type="java.lang.AssertionError" message="expected [mQkC44ipf3Fv@mailinator.com] but found [eEeiUvQKYwBs@mailinator.com]">
      <![CDATA[java.lang.AssertionError: expected [mQkC44ipf3Fv@mailinator.com] but found [eEeiUvQKYwBs@mailinator.com]
	at automationFramework.TestCases.UpdateAddressTest.updateAddress(UpdateAddressTest.java:115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- updateAddress -->
  <testcase name="updateAddressCancel" time="12.78" classname="automationFramework.TestCases.UpdateAddressTest"/>
  <testcase name="addNewAddressCheckRequiredFields" time="12.446" classname="automationFramework.TestCases.UpdateAddressTest"/>
  <testcase name="addNewAddressInvalidData" time="13.577" classname="automationFramework.TestCases.UpdateAddressTest">
    <failure type="java.lang.AssertionError" message="expected [Postal Code is invalid.] but found [Zip Code is invalid.]">
      <![CDATA[java.lang.AssertionError: expected [Postal Code is invalid.] but found [Zip Code is invalid.]
	at automationFramework.TestCases.UpdateAddressTest.addNewAddressInvalidData(UpdateAddressTest.java:200)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- addNewAddressInvalidData -->
  <testcase name="updateContact" time="16.198" classname="automationFramework.TestCases.UpdateContactTest">
    <failure type="java.lang.AssertionError" message="expected [indy] but found [robert]">
      <![CDATA[java.lang.AssertionError: expected [indy] but found [robert]
	at automationFramework.TestCases.UpdateContactTest.updateContact(UpdateContactTest.java:60)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- updateContact -->
  <testcase name="updateContactCancel" time="12.461" classname="automationFramework.TestCases.UpdateContactTest">
    <failure type="java.lang.AssertionError" message="expected [4033311371] but found [4033311371,undefined,undefined]">
      <![CDATA[java.lang.AssertionError: expected [4033311371] but found [4033311371,undefined,undefined]
	at automationFramework.TestCases.UpdateContactTest.updateContactCancel(UpdateContactTest.java:88)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- updateContactCancel -->
  <testcase name="updateContactAndAddress" time="20.037" classname="automationFramework.TestCases.UpdateContactTest"/>
  <testcase name="updateContactAndAddressCancel" time="14.902" classname="automationFramework.TestCases.UpdateContactTest"/>
  <testcase name="updateContactCheckRequiredFields" time="11.084" classname="automationFramework.TestCases.UpdateContactTest"/>
  <testcase name="updateContactInvalidPhone" time="15.101" classname="automationFramework.TestCases.UpdateContactTest">
    <failure type="java.lang.AssertionError" message="expected [phone[0].number errors.general.invalid.phone.number] but found []">
      <![CDATA[java.lang.AssertionError: expected [phone[0].number errors.general.invalid.phone.number] but found []
	at automationFramework.TestCases.UpdateContactTest.updateContactInvalidPhone(UpdateContactTest.java:188)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- updateContactInvalidPhone -->
  <testcase name="updateContactInvalidEmail" time="12.801" classname="automationFramework.TestCases.UpdateContactTest"/>
  <testcase name="updateContactInvalidUserName" time="10.252" classname="automationFramework.TestCases.UpdateContactTest"/>
  <testcase name="updateContactInvalidPin" time="11.659" classname="automationFramework.TestCases.UpdateContactTest"/>
  <testcase name="updateContactSecurityAnswermissing" time="9.913" classname="automationFramework.TestCases.UpdateContactTest"/>
  <testcase name="updateContactOtherPhonesMissing" time="13.302" classname="automationFramework.TestCases.UpdateContactTest"/>
  <testcase name="updateNonPrimaryFundingTest" time="34.691" classname="automationFramework.TestCases.UpdateFundingTest"/>
  <testcase name="updateNonPrimaryFundingCancelTest" time="28.377" classname="automationFramework.TestCases.UpdateFundingTest"/>
  <testcase name="updatePrimaryFundingTest" time="21.577" classname="automationFramework.TestCases.UpdateFundingTest"/>
  <testcase name="updatePrimaryFundingCancelTest" time="17.747" classname="automationFramework.TestCases.UpdateFundingTest"/>
</testsuite> <!-- ChromeTest -->
